version: 0.0
os: linux
hooks:
  AfterInstall:
    - location: aws/scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/application-start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: aws/scripts/validate-service.sh
      timeout: 300
      runas: root